/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogPalmLeafVsBambooVsBagasseRouteImport } from './routes/blog.palm-leaf-vs-bamboo-vs-bagasse'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogPalmLeafVsBambooVsBagasseRoute =
  BlogPalmLeafVsBambooVsBagasseRouteImport.update({
    id: '/blog/palm-leaf-vs-bamboo-vs-bagasse',
    path: '/blog/palm-leaf-vs-bamboo-vs-bagasse',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/palm-leaf-vs-bamboo-vs-bagasse': typeof BlogPalmLeafVsBambooVsBagasseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/palm-leaf-vs-bamboo-vs-bagasse': typeof BlogPalmLeafVsBambooVsBagasseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/blog/palm-leaf-vs-bamboo-vs-bagasse': typeof BlogPalmLeafVsBambooVsBagasseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/sitemap.xml'
    | '/blog/palm-leaf-vs-bamboo-vs-bagasse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products'
    | '/sitemap.xml'
    | '/blog/palm-leaf-vs-bamboo-vs-bagasse'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/sitemap.xml'
    | '/blog/palm-leaf-vs-bamboo-vs-bagasse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogPalmLeafVsBambooVsBagasseRoute: typeof BlogPalmLeafVsBambooVsBagasseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/palm-leaf-vs-bamboo-vs-bagasse': {
      id: '/blog/palm-leaf-vs-bamboo-vs-bagasse'
      path: '/blog/palm-leaf-vs-bamboo-vs-bagasse'
      fullPath: '/blog/palm-leaf-vs-bamboo-vs-bagasse'
      preLoaderRoute: typeof BlogPalmLeafVsBambooVsBagasseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogPalmLeafVsBambooVsBagasseRoute: BlogPalmLeafVsBambooVsBagasseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
